version: '3.4'

services:

  productgrpc.internal.local:
    image: ${DOCKER_REGISTRY-}productgrpcinternallocal
    container_name: productgrpc.internal.local
    build:
      context: .
      dockerfile: ProductGrpc/Dockerfile
    expose:
    - 53441
    ports:
    - 53441:53441

  product.grpc.db:
    image: postgres
    container_name: product.grpc.db
    restart: always
    expose:
      - 5438
    ports:
      - 5438:5438
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: products
      PGPORT: 5438

     