version: '3.4'

services:
  productgrpc:
    image: ${DOCKER_REGISTRY-}productgrpc
    build:
      context: .
      dockerfile: ProductGrpc/Dockerfile
    expose:
    - 443
    ports:
    - 443:443
    
