version: '3.4'

services:

  productgrpc.internal.local:
    image: ${DOCKER_REGISTRY-}productgrpcinternallocal
    container_name: productgrpc.internal.local
    build:
      context: .
      dockerfile: ProductGrpc/Dockerfile
    expose:
    - 53443
    ports:
    - 53443:53443

  product.grpc.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: product.grpc.db
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Iloveswing77!"
      ACCEPT_EULA: "Y"

     