version: '3.4'

services:

  productgrpc:
    image: ${DOCKER_REGISTRY-}productgrpc
    build:
      context: .
      dockerfile: ProductGrpc/Dockerfile
    expose:
    - 443
    ports:
    - 443:443

  product.grpc.db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: product.grpc.db
    restart: always
    expose:
      - 14033
    ports:
      - 14033:1433
    environment:
      SA_PASSWORD: "Iloveswing77!"
      ACCEPT_EULA: "Y"

     