version: '3.4'

## docker-compose docker-compose.yml up
## docker-compose docker-compose.yml down

services:
  productgrpc:
    image: ${DOCKER_REGISTRY-}productgrpc
    build:
      context: .
      dockerfile: ProductGrpc/Dockerfile
    expose:
    - 443
    ports:
    - 443:443

  product.grpc.db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: product.grpc.db
    restart: always
    expose:
      - 1433
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Iloveswing77!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"

     